[project]
name = "markdowns-organizer"
version = "0.1.0"
description = "Streamlit app to organize markdown data into folders"
authors = [
    {name = "siddarthasagar", email = "siddarthasagar@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.43.1,<2.0.0",
]

[dependency-groups]
dev = [
    "pyupgrade>=3.21.2",
    "pytest>=8.3.0",
    "ruff>=0.15.13",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/markdowns_organizer"]

[tool.ruff]
line-length = 88
target-version = "py313"

[tool.ruff.lint]
select = ["ALL"]
ignore = ["E501", "CPY001", "D100", "D104"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.pytest.ini_options]
testpaths = ["tests"]
